-- Femiro production data, roles, RLS, and image storage.
-- Run once in Supabase SQL Editor.

create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text,
  role text not null default 'user' check (role in ('user', 'employee', 'admin')),
  created_at timestamptz not null default now()
);

alter table public.profiles add column if not exists display_name text;
alter table public.profiles add column if not exists role text not null default 'user';

create table if not exists public.products (
  id bigint primary key generated by default as identity,
  name text not null,
  type text not null,
  price numeric(12,2) not null check (price >= 0),
  old_price numeric(12,2),
  image text not null,
  hover text not null,
  tag text,
  description text not null,
  colors text[] not null default '{}',
  sizes text[] not null default '{}',
  has_colors boolean not null default false,
  in_stock boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.categories (
  name text primary key,
  created_at timestamptz not null default now()
);

create table if not exists public.hero_settings (
  id boolean primary key default true check (id),
  eyebrow text not null,
  headline text not null,
  subtitle text not null,
  image_url text not null,
  button_text text not null,
  button_link text not null default '/shop',
  updated_at timestamptz not null default now()
);

create table if not exists public.discounts (
  id uuid primary key default gen_random_uuid(),
  code text not null unique,
  discount_percent numeric(5,2) not null check (discount_percent >= 0 and discount_percent <= 100),
  fixed_amount numeric(12,2),
  type text not null default 'percent' check (type in ('percent', 'fixed')),
  min_spend numeric(12,2) not null default 0 check (min_spend >= 0),
  scope text not null default 'storewide' check (scope in ('storewide', 'category', 'products')),
  category_target text,
  product_ids bigint[] not null default '{}',
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.addresses (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  mobile text not null,
  street text not null,
  city text not null,
  state text not null,
  pincode text not null,
  landmark text,
  tag text not null check (tag in ('Home', 'Office', 'Other')),
  is_default boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete restrict,
  items jsonb not null,
  total numeric(12,2) not null check (total >= 0),
  currency text not null default 'INR' check (currency = 'INR'),
  status text not null default 'Processing' check (status in ('Processing', 'Shipped', 'Delivered', 'Cancelled', 'Payment Pending')),
  delivery_address text not null,
  customer_email text,
  customer_phone text,
  razorpay_order_id text unique,
  razorpay_payment_id text unique,
  paid_at timestamptz,
  created_at timestamptz not null default now()
);

alter table public.products add column if not exists colors text[] not null default '{}';
alter table public.products add column if not exists sizes text[] not null default '{}';
alter table public.products add column if not exists has_colors boolean not null default false;
alter table public.products add column if not exists in_stock boolean not null default true;
alter table public.products add column if not exists created_at timestamptz not null default now();
alter table public.products add column if not exists updated_at timestamptz not null default now();
alter table public.orders add column if not exists user_id uuid references auth.users(id) on delete restrict;
alter table public.orders add column if not exists razorpay_order_id text unique;
alter table public.orders add column if not exists razorpay_payment_id text unique;
alter table public.orders add column if not exists paid_at timestamptz;
alter table public.orders add column if not exists customer_email text;
alter table public.orders add column if not exists customer_phone text;

create or replace function public.is_staff()
returns boolean language sql stable security definer set search_path = public as $$
  select coalesce(auth.jwt() -> 'app_metadata' ->> 'role', '') in ('admin', 'employee')
    or exists (select 1 from public.profiles where id = auth.uid() and role in ('admin', 'employee'));
$$;

create or replace function public.is_admin()
returns boolean language sql stable security definer set search_path = public as $$
  select coalesce(auth.jwt() -> 'app_metadata' ->> 'role', '') = 'admin'
    or exists (select 1 from public.profiles where id = auth.uid() and role = 'admin');
$$;

create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  insert into public.profiles (id, email, display_name)
  values (new.id, new.email, new.raw_user_meta_data ->> 'name');
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

alter table public.profiles enable row level security;
alter table public.products enable row level security;
alter table public.categories enable row level security;
alter table public.hero_settings enable row level security;
alter table public.discounts enable row level security;
alter table public.addresses enable row level security;
alter table public.orders enable row level security;

drop policy if exists profiles_self_read on public.profiles;
create policy profiles_self_read on public.profiles for select using (id = auth.uid() or public.is_admin());
drop policy if exists profiles_admin_write on public.profiles;
create policy profiles_admin_write on public.profiles for update using (public.is_admin()) with check (public.is_admin());

drop policy if exists products_public_read on public.products;
create policy products_public_read on public.products for select using (true);
drop policy if exists products_staff_write on public.products;
create policy products_staff_write on public.products for all using (public.is_staff()) with check (public.is_staff());

drop policy if exists categories_public_read on public.categories;
create policy categories_public_read on public.categories for select using (true);
drop policy if exists categories_admin_write on public.categories;
create policy categories_admin_write on public.categories for all using (public.is_admin()) with check (public.is_admin());

drop policy if exists hero_public_read on public.hero_settings;
create policy hero_public_read on public.hero_settings for select using (true);
drop policy if exists hero_admin_write on public.hero_settings;
create policy hero_admin_write on public.hero_settings for all using (public.is_admin()) with check (public.is_admin());

drop policy if exists discounts_public_read_active on public.discounts;
create policy discounts_public_read_active on public.discounts for select using (active = true or public.is_staff());
drop policy if exists discounts_admin_write on public.discounts;
create policy discounts_admin_write on public.discounts for all using (public.is_admin()) with check (public.is_admin());

drop policy if exists addresses_owner_all on public.addresses;
create policy addresses_owner_all on public.addresses for all using (user_id = auth.uid()) with check (user_id = auth.uid());

drop policy if exists orders_owner_read on public.orders;
create policy orders_owner_read on public.orders for select using (user_id = auth.uid() or public.is_staff());
drop policy if exists orders_staff_update on public.orders;
create policy orders_staff_update on public.orders for update using (public.is_staff()) with check (public.is_staff());

insert into storage.buckets (id, name, public) values ('product-images', 'product-images', true)
on conflict (id) do nothing;

drop policy if exists product_images_public_read on storage.objects;
create policy product_images_public_read on storage.objects for select using (bucket_id = 'product-images');
drop policy if exists product_images_staff_write on storage.objects;
create policy product_images_staff_write on storage.objects for insert with check (bucket_id = 'product-images' and public.is_staff());
drop policy if exists product_images_staff_update on storage.objects;
create policy product_images_staff_update on storage.objects for update using (bucket_id = 'product-images' and public.is_staff());
drop policy if exists product_images_staff_delete on storage.objects;
create policy product_images_staff_delete on storage.objects for delete using (bucket_id = 'product-images' and public.is_staff());
